import type { WorkItem, WorkItemEvent } from "./types.js";

export const mockFeatures: WorkItem[] = [
  {
    id: "checkout-redesign-001",
    title: "Cart drawer refactor",
    description: "Refactor the slide-out shopping cart drawer for optimized performance.",
    state: "active",
    phase: "implement",
    phase_group: "create",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: "claude",
    project: "Checkout Redesign",
    branch: "feat/cart-drawer-refactor",
    pr_url: null,
    created_at: "2026-07-28T09:00:00Z",
    updated_at: "2026-07-28T10:15:00Z",
  },
  {
    id: "checkout-redesign-002",
    title: "Payment retries",
    description: "Clarify the retry behavior before implementation proceeds.",
    state: "blocked",
    phase: "review",
    phase_group: "create",
    work_item_type: "feature",
    blocked_reason: "clarification-required",
    assignee: "codex",
    project: "Checkout Redesign",
    branch: "feat/payment-retries",
    pr_url: null,
    created_at: "2026-07-28T09:10:00Z",
    updated_at: "2026-07-28T10:20:00Z",
  },
  {
    id: "checkout-redesign-003",
    title: "Empty state copy",
    description: "Prepare concise copy for a new checkout empty state.",
    state: "closed",
    phase: "integrate",
    phase_group: "integrate",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: "human",
    project: "Checkout Redesign",
    branch: null,
    pr_url: null,
    created_at: "2026-07-28T09:20:00Z",
    updated_at: "2026-07-28T10:30:00Z",
  },
  {
    id: "search-revamp-001",
    title: "Fuzzy match ranking",
    description: "Define ranking behavior for fuzzy search results.",
    state: "parked",
    phase: "spec",
    phase_group: "define",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: null,
    project: "Search Revamp",
    branch: null,
    pr_url: null,
    created_at: "2026-07-28T09:30:00Z",
    updated_at: "2026-07-28T09:30:00Z",
  },
  {
    id: "search-revamp-002",
    title: "Search analytics",
    description: "Capture the planned search analytics work.",
    state: "parked",
    phase: "spec",
    phase_group: "define",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: null,
    project: "Search Revamp",
    branch: null,
    pr_url: null,
    created_at: "2026-07-28T09:35:00Z",
    updated_at: "2026-07-28T09:35:00Z",
  },
  {
    id: "billing-v2-001",
    title: "Invoice PDF export",
    description: "Await approval for the invoice PDF export approach.",
    state: "blocked",
    phase: "plan",
    phase_group: "define",
    work_item_type: "feature",
    blocked_reason: "approval-required",
    assignee: "claude",
    project: "Billing v2",
    branch: "feat/invoice-pdf-export",
    pr_url: null,
    created_at: "2026-07-28T09:40:00Z",
    updated_at: "2026-07-28T10:00:00Z",
  },
  {
    id: "billing-v2-002",
    title: "Proration logic",
    description: "Define proration calculations for Billing v2.",
    state: "parked",
    phase: "spec",
    phase_group: "define",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: null,
    project: "Billing v2",
    branch: null,
    pr_url: null,
    created_at: "2026-07-28T09:45:00Z",
    updated_at: "2026-07-28T09:45:00Z",
  },
  {
    id: "notifications-001",
    title: "Digest emails",
    description: "Plan digest email delivery for notifications.",
    state: "parked",
    phase: "spec",
    phase_group: "define",
    work_item_type: "feature",
    blocked_reason: null,
    assignee: null,
    project: "Notifications",
    branch: null,
    pr_url: null,
    created_at: "2026-07-28T09:50:00Z",
    updated_at: "2026-07-28T09:50:00Z",
  },
];

export const mockEvents: Record<string, WorkItemEvent[]> = {
  "checkout-redesign-001": [
    {
      work_item_id: "checkout-redesign-001",
      timestamp: "2026-07-28T09:05:00Z",
      actor: "claude",
      type: "agent.note",
      summary: "The cart drawer component structure is ready for refinement.",
      artifact_path: null,
      payload: {},
    },
  ],
  "checkout-redesign-002": [
    {
      work_item_id: "checkout-redesign-002",
      timestamp: "2026-07-28T10:00:00Z",
      actor: "codex",
      type: "agent.question",
      summary: "Which retry policy should be applied to declined payments?",
      artifact_path: null,
      payload: { decision_id: "payment-retry-policy", options: ["Approve changes", "Keep current policy"] },
    },
  ],
  "checkout-redesign-003": [],
  "search-revamp-001": [],
  "search-revamp-002": [],
  "billing-v2-001": [
    {
      work_item_id: "billing-v2-001",
      timestamp: "2026-07-28T10:10:00Z",
      actor: "claude",
      type: "agent.question",
      summary: "Approve the proposed PDF rendering library before planning continues.",
      artifact_path: null,
      payload: {},
    },
  ],
  "billing-v2-002": [],
  "notifications-001": [],
};

export const mockPlanMarkdown: Record<string, string> = {
  "checkout-redesign-001": "# Cart drawer refactor\n\n- Extract drawer state\n- Add accessibility checks\n- Verify checkout transitions",
  "checkout-redesign-002": "# Payment retries\n\n- Confirm retry policy\n- Update failure handling\n- Review decline messaging",
};

export const mockDiffs: Record<string, string> = {
  "checkout-redesign-001": "@@ -12,3 +12,5 @@\n-const open = false;\n+const [open, setOpen] = useState(false);",
};

export const mockAgentLogs: Record<string, string[]> = {
  "checkout-redesign-001": ["$ writing CartDrawer.tsx", "+ 42 lines"],
  "checkout-redesign-002": ["$ waiting for operator decision"],
};
